//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2.ora_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Neptun { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<decimal> AverageGrade { get; set; }
        public bool IsActive { get; set; }
    }
}
